version: '3'
services:
  # php-fpm
  php-fpm:
    container_name: cross_cookie_php_fpm
    build: ./php-fpm
    working_dir: /usr/share/nginx/html
    ports:
      - "9000"
    volumes:
      - ${WWW_DIR}:/usr/share/nginx/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    environment: 
      - WWW_DIR=/usr/share/nginx/html

  # web server
  nginx:
    container_name: cross_cookie_nginx
    image: nginx:1.13.12
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # app
      - ${WWW_DIR}:/usr/share/nginx/html
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # nginx SSL
      - ./nginx/ssl/:/etc/nginx/ssl/:ro
    depends_on:
      - php-fpm
